<?php
// Products Tab Content
?>
<!-- Add Product Tab -->
<div id="products" class="tab-content">
    <div class="section">
        <h2 data-translate="inventory.addProduct">📦 Add New Product</h2>
        <form method="POST">
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                <div>
                    <div class="form-group">
                        <label data-translate="inventory.productCode">Product Code:</label>
                        <div
                            style="padding: 10px; background: #f8f9fa; border: 2px solid #e9ecef; border-radius: 5px; color: #666; font-weight: bold;">
                            Will be auto-generated
                        </div>
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.autoGenerated">Product code will be automatically created
                            when you save</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.brand"><span style="color: red;">*</span> Brand:</label>
                        <input type="text" name="brand" required
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.model"><span style="color: red;">*</span> Model:</label>
                        <input type="text" name="model" required
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.purchasePrice"><span style="color: red;">*</span> Purchase Price (Cost):</label>
                        <input type="number" name="purchase_price" step="0.01" min="0.01" required
                            placeholder="What you pay to buy this product"
                            style="width: 70%; max-width: 70%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.purchasePriceHelp">The cost price you pay to suppliers</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.minPrice"><span style="color: red;">*</span> Minimum Selling Price:</label>
                        <input type="number" name="min_selling_price" step="0.01" min="0.01" required
                            placeholder="Lowest price allowed for sale"
                            style="width: 70%; max-width: 70%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.minPriceHelp">Staff cannot sell below this price</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.suggestedPrice"><span style="color: red;">*</span> Suggested Selling Price:</label>
                        <input type="number" name="suggested_price" step="0.01" min="0.01" required
                            placeholder="Recommended selling price"
                            style="width: 70%; max-width: 70%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.suggestedPriceHelp">Default price shown in receipts (can be
                            changed)</small>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <label data-translate="inventory.stockQuantity"><span style="color: red;">*</span> Stock Quantity:</label>
                        <input type="number" name="stock" min="1" required
                            placeholder="Enter stock quantity (must be greater than 0)"
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;"></small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.serialNumber">Serial Number:</label>
                        <input type="text" name="serial_number" 
                            placeholder="Enter serial number (optional)"
                            style="width: 70%; max-width: 70%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.serialHelp">Unique serial number for tracking</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.color">Color:</label>
                        <input type="text" name="color" 
                            placeholder="Enter product color"
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.colorHelp">Product color (e.g., Black, White, Blue)</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.supplier">Supplier:</label>
                        <select name="supplier_id" id="supplier-select"
                            style="width: 70%; max-width: 70%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                            <option value="" data-translate="inventory.selectSupplier">Select Supplier</option>
                        </select>
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.supplierHelp">Choose supplier for this product</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.hasImei">Has IMEI:</label>
                        <select name="has_imei" id="has-imei-select"
                            style="width: 30%; max-width: 30%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                            <option value="0" data-translate="common.no">No</option>
                            <option value="1" data-translate="common.yes">Yes</option>
                        </select>
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.imeiHelp">Does this product have IMEI?</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.minStock">Minimum Stock:</label>
                        <input type="number" name="min_stock" placeholder="Leave empty for no minimum stock"
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.minStockHelp">Optional: Set minimum stock level for alerts</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.category">Category:</label>
                        <select name="category_id" id="category-select"
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px;">
                            <option value="" data-translate="inventory.selectCategory">Select Category</option>
                            <option value="1" data-translate="inventory.phones">Phones</option>
                            <option value="2" data-translate="inventory.airpods">AirPods</option>
                            <option value="3" data-translate="inventory.watch">Watch</option>
                            <option value="4" data-translate="inventory.accessories">Accessories</option>
                            <option value="5" data-translate="inventory.tablets">Tablets</option>
                        </select>
                        <small style="color: #666; font-size: 12px;" data-translate="inventory.categoryHelp">Choose product category</small>
                    </div>
                    <div class="form-group">
                        <label data-translate="inventory.description">Description:</label>
                        <textarea name="description" rows="3"
                            style="width: 50%; max-width: 50%; padding: 10px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px; resize: vertical;"></textarea>
                    </div>
                </div>
            </div>
            <button type="submit" name="add_product" class="btn" data-translate="inventory.addProduct">Add Product</button>
        </form>
    </div>
</div>
